import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  hashKernelShapeArtifactFixtureWitness,
  hashKernelShapeSemanticObservation,
} from "../src/conformance.js";
import { getOcctShapeArtifactCodecCandidate } from "../src/internal/occt-artifact-candidate.js";
import type { KernelShape, KernelShapeArtifactCapabilities } from "../src/kernel.js";
import { createOcctKernel } from "../src/occt-kernel.js";
import {
  observeKernelShapeSemantics,
  type KernelShapeSemanticNotApplicableFeature,
  type KernelShapeSemanticObservationPlan,
} from "../src/shape-semantic-observation.js";

type FixtureVersion = 1 | 2;
type Mode = "check" | "write";

interface Options {
  readonly help: boolean;
  readonly mode: Mode;
  readonly version?: FixtureVersion;
}

interface EncodedFixture {
  readonly bytes: Uint8Array;
  readonly capabilities: KernelShapeArtifactCapabilities;
  readonly semanticWitness: string;
  readonly version: FixtureVersion;
}

const projectRoot = fileURLToPath(new URL("..", import.meta.url));
const maximumArtifactBytes = 64 * 1024 * 1024;
const fixtureFeature = "fixture.asymmetric-role-box";
const fixtureBaseName = "occt-shape-candidate";
// Missing fixtures for versions outside this list are reported as pending so a
// codec revision can land before its generated bytes receive separate review.
// Add a version here in the same commit that approves its fixture.
const approvedFixtureVersions: readonly FixtureVersion[] = Object.freeze([1, 2]);

const notApplicableFeatures: readonly KernelShapeSemanticNotApplicableFeature[] =
  Object.freeze([
    {
      feature: "extrude",
      reason:
        "Direct candidate artifact restoration fixture; downstream extrude behavior is outside this bounded case.",
    },
    {
      feature: "revolve",
      reason:
        "Direct candidate artifact restoration fixture; downstream revolve behavior is outside this bounded case.",
    },
    {
      feature: "loft",
      reason:
        "Direct candidate artifact restoration fixture; downstream loft behavior is outside this bounded case.",
    },
    {
      feature: "sweep",
      reason:
        "Direct candidate artifact restoration fixture; downstream sweep behavior is outside this bounded case.",
    },
    {
      feature: "circularArcSweep",
      reason:
        "Direct candidate artifact restoration fixture; downstream circular-arc sweep behavior is outside this bounded case.",
    },
    {
      feature: "compositeSweep",
      reason:
        "Direct candidate artifact restoration fixture; downstream composite sweep behavior is outside this bounded case.",
    },
    {
      feature: "boolean",
      reason:
        "Direct candidate artifact restoration fixture; downstream Boolean behavior is outside this bounded case.",
    },
    {
      feature: "transform",
      reason:
        "Direct candidate artifact restoration fixture; downstream transform behavior is outside this bounded case.",
    },
    {
      feature: "fillet",
      reason:
        "Direct candidate artifact restoration fixture; downstream fillet behavior is outside this bounded case.",
    },
    {
      feature: "chamfer",
      reason:
        "Direct candidate artifact restoration fixture; downstream chamfer behavior is outside this bounded case.",
    },
    {
      feature: "shell",
      reason:
        "Direct candidate artifact restoration fixture; downstream shell behavior is outside this bounded case.",
    },
    {
      feature: "offset",
      reason:
        "Direct candidate artifact restoration fixture; downstream offset behavior is outside this bounded case.",
    },
  ]);

// This ID describes the semantic observation protocol, not the artifact byte
// format. Keep it stable across a byte-only codec revision so the semantic
// witness remains an independent control.
const observationPlan: KernelShapeSemanticObservationPlan = Object.freeze({
  id: "occt-shape-artifact-candidate-release-v1",
  meshes: Object.freeze([{ id: "default" }]),
  topology: "required",
  nativeExchanges: Object.freeze([]),
  probes: Object.freeze([]),
  notApplicableFeatures,
});

function usage(): string {
  return `Usage: tsx scripts/generate-occt-artifact-fixture.ts [options]

Generate or verify the deterministic stock-OCCT asymmetric-box artifact fixture.

Options:
  --check                 Verify the fixture (default; never writes)
  --write                 Explicitly create or replace the fixture
  --version v1|v2         Require one exact currently wired format version
  --help                  Show this help
`;
}

function parseVersion(value: string | undefined): FixtureVersion {
  if (value === "v1" || value === "1") return 1;
  if (value === "v2" || value === "2") return 2;
  throw new Error("--version must be v1 or v2");
}

function parseOptions(arguments_: readonly string[]): Options {
  const values = arguments_[0] === "--" ? arguments_.slice(1) : arguments_;
  let explicitMode: Mode | undefined;
  let version: FixtureVersion | undefined;
  let help = false;
  for (let index = 0; index < values.length; index += 1) {
    const argument = values[index];
    if (argument === "--help" || argument === "-h") {
      help = true;
      continue;
    }
    if (argument === "--check" || argument === "--write") {
      const nextMode = argument.slice(2) as Mode;
      if (explicitMode !== undefined && explicitMode !== nextMode) {
        throw new Error("--check and --write are mutually exclusive");
      }
      explicitMode = nextMode;
      continue;
    }
    if (argument === "--version") {
      if (version !== undefined) throw new Error("--version may be specified once");
      version = parseVersion(values[index + 1]);
      index += 1;
      continue;
    }
    if (argument?.startsWith("--version=")) {
      if (version !== undefined) throw new Error("--version may be specified once");
      version = parseVersion(argument.slice("--version=".length));
      continue;
    }
    throw new Error(`Unknown argument '${String(argument)}'\n\n${usage()}`);
  }
  return {
    help,
    mode: explicitMode ?? "check",
    ...(version === undefined ? {} : { version }),
  };
}

function fixturePath(version: FixtureVersion): string {
  return resolve(
    projectRoot,
    "tests/fixtures",
    `${fixtureBaseName}-v${version}-asymmetric-box.b64`,
  );
}

function canonicalBase64(bytes: Uint8Array): string {
  const encoded = Buffer.from(bytes).toString("base64");
  const lines: string[] = [];
  for (let offset = 0; offset < encoded.length; offset += 100) {
    lines.push(encoded.slice(offset, offset + 100));
  }
  return `${lines.join("\n")}\n`;
}

function sameCapabilities(
  first: KernelShapeArtifactCapabilities,
  second: KernelShapeArtifactCapabilities,
): boolean {
  return (
    first.protocolVersion === second.protocolVersion &&
    first.format === second.format &&
    first.formatVersion === second.formatVersion &&
    first.compatibilityFingerprint === second.compatibilityFingerprint
  );
}

function failResult(label: string, result: { readonly diagnostics: unknown }): never {
  throw new Error(`${label}: ${JSON.stringify(result.diagnostics)}`);
}

async function semanticWitness(
  kernel: Awaited<ReturnType<typeof createOcctKernel>>,
  shape: KernelShape,
): Promise<string> {
  const observation = await observeKernelShapeSemantics(
    kernel,
    shape,
    observationPlan,
    { limits: { maxObservationBytes: maximumArtifactBytes } },
  );
  if (!observation.ok) failResult("Semantic observation failed", observation);
  const witness = await hashKernelShapeSemanticObservation(observation.value, {
    maxBytes: maximumArtifactBytes,
  });
  if (!witness.ok) failResult("Semantic witness hashing failed", witness);
  return witness.value;
}

async function encodeOnce(
  requestedVersion: FixtureVersion | undefined,
  observeSource: boolean,
): Promise<EncodedFixture> {
  const kernel = await createOcctKernel();
  let source: KernelShape | undefined;
  try {
    const candidate = getOcctShapeArtifactCodecCandidate(kernel);
    if (candidate === undefined || kernel.box === undefined) {
      throw new Error("The stock OCCT artifact candidate is unavailable");
    }
    const rawVersion = candidate.capabilities.formatVersion;
    if (rawVersion !== 1 && rawVersion !== 2) {
      throw new Error(`Unsupported wired OCCT artifact format version ${rawVersion}`);
    }
    const version = rawVersion as FixtureVersion;
    if (requestedVersion !== undefined && requestedVersion !== version) {
      throw new Error(
        `Requested fixture v${requestedVersion}, but the current candidate encodes v${version}; no fixture was read or written`,
      );
    }
    source = kernel.box([2, 3, 5], false, { feature: fixtureFeature });

    // This must be the first evaluator-observable operation on the source.
    const output = await candidate.encodeShapeArtifact(source, {
      feature: fixtureFeature,
      maxArtifactBytes: maximumArtifactBytes,
    });
    if (
      !(output instanceof Uint8Array) ||
      output.byteOffset !== 0 ||
      output.byteLength === 0 ||
      output.byteLength !== output.buffer.byteLength ||
      output.byteLength > maximumArtifactBytes
    ) {
      throw new Error("The OCCT candidate returned malformed fixture bytes");
    }
    const bytes = output.slice();
    return {
      bytes,
      capabilities: candidate.capabilities,
      semanticWitness: observeSource ? await semanticWitness(kernel, source) : "",
      version,
    };
  } finally {
    if (source !== undefined) kernel.disposeShape(source);
    kernel.dispose();
  }
}

async function decodedSemanticWitness(
  fixture: EncodedFixture,
): Promise<string> {
  const kernel = await createOcctKernel();
  let decoded: KernelShape | undefined;
  try {
    const candidate = getOcctShapeArtifactCodecCandidate(kernel);
    if (candidate === undefined) {
      throw new Error("The stock OCCT artifact candidate is unavailable");
    }
    if (!sameCapabilities(fixture.capabilities, candidate.capabilities)) {
      throw new Error("Fresh OCCT candidate capabilities are not deterministic");
    }
    decoded = await candidate.decodeShapeArtifact(fixture.bytes.slice(), {
      feature: fixtureFeature,
      maxArtifactBytes: maximumArtifactBytes,
    });
    return await semanticWitness(kernel, decoded);
  } finally {
    if (decoded !== undefined) kernel.disposeShape(decoded);
    kernel.dispose();
  }
}

async function generate(
  requestedVersion: FixtureVersion | undefined,
): Promise<EncodedFixture> {
  const first = await encodeOnce(requestedVersion, true);
  const second = await encodeOnce(first.version, false);
  if (!sameCapabilities(first.capabilities, second.capabilities)) {
    throw new Error("Fresh OCCT candidate capabilities are not deterministic");
  }
  if (!Buffer.from(first.bytes).equals(second.bytes)) {
    throw new Error("Fresh OCCT candidate encodes are not byte-identical");
  }
  const decodedWitness = await decodedSemanticWitness(first);
  if (decodedWitness !== first.semanticWitness) {
    throw new Error(
      `Decoded semantic witness differs from the source: ${first.semanticWitness} != ${decodedWitness}`,
    );
  }
  return first;
}

async function main(arguments_: readonly string[]): Promise<void> {
  const options = parseOptions(arguments_);
  if (options.help) {
    process.stdout.write(usage());
    return;
  }

  const fixture = await generate(options.version);
  const path = fixturePath(fixture.version);
  const expectedText = canonicalBase64(fixture.bytes);
  const witness = await hashKernelShapeArtifactFixtureWitness(fixture.bytes, {
    maxBytes: maximumArtifactBytes,
  });
  if (!witness.ok) failResult("Fixture witness hashing failed", witness);

  if (options.mode === "check") {
    let actualText: string | undefined;
    try {
      actualText = await readFile(path, "utf8");
    } catch (error) {
      if (
        typeof error === "object" &&
        error !== null &&
        "code" in error &&
        error.code === "ENOENT"
      ) {
        if (approvedFixtureVersions.includes(fixture.version)) {
          throw new Error(
            `The approved v${fixture.version} fixture is missing at ${path}; no file was written`,
          );
        }
        process.stdout.write(
          `OCCT artifact fixture v${fixture.version} is pending review; no file was written.\n`,
        );
      } else {
        throw error;
      }
    }
    if (actualText !== undefined && actualText !== expectedText) {
      throw new Error(
        `The reviewed v${fixture.version} fixture differs from the deterministic encoder output; no file was written`,
      );
    }
    if (actualText !== undefined) {
      process.stdout.write(`OCCT artifact fixture v${fixture.version} is current.\n`);
    }
  } else {
    await writeFile(path, expectedText, { encoding: "utf8", mode: 0o644 });
    process.stdout.write(`Wrote OCCT artifact fixture v${fixture.version}.\n`);
  }

  process.stdout.write(
    [
      `path: ${path}`,
      `bytes: ${fixture.bytes.byteLength}`,
      `fixture witness: ${witness.value}`,
      `semantic witness: ${fixture.semanticWitness}`,
      `format: ${fixture.capabilities.format}@${fixture.capabilities.formatVersion}`,
      `fingerprint: ${fixture.capabilities.compatibilityFingerprint}`,
    ].join("\n") + "\n",
  );
}

main(process.argv.slice(2)).catch((error: unknown) => {
  process.stderr.write(
    `[occt-artifact-fixture] ${error instanceof Error ? error.message : String(error)}\n`,
  );
  process.exitCode = 1;
});
