export {
  CadError,
  diagnostic,
  failure,
  hasErrors,
  success,
  type CadResult,
  type Diagnostic,
  type DiagnosticCode,
  type DiagnosticSeverity,
} from "./core/result.js";
export type { Mat4, Vec2, Vec3 } from "./core/math.js";
export {
  DesignBuilder,
  ModelRef,
  ProfileRef,
  PathRef,
  SolidRef,
  PartRef,
  AssemblyRef,
  MaterialRef,
  TopologyReferenceRef,
  AssemblyBuilder,
  ConfigurationBuilder,
  design,
  plane,
  tf,
  type DesignOptions,
  type MaterialOptions,
  type PartOptions,
  type CompositePathSegmentExpression,
  type ConfigurationOptions,
  type ParameterOptions,
  type Plane,
  type TopologyReferenceOptions,
} from "./design.js";
export {
  Expression,
  Parameter,
  angleVec3,
  cm,
  deg,
  evaluateExpression,
  expr,
  expressionDependencies,
  fromExpressionIR,
  gramsPerCubicCentimeter,
  inch,
  kgPerCubicMeter,
  kgPerCubicMillimeter,
  meters,
  mm,
  rad,
  scalar,
  scalarVec3,
  vec2,
  vec3,
  type AngleExpression,
  type AngleVec3Expression,
  type Dimension,
  type ExpressionContext,
  type ExpressionIR,
  type LengthExpression,
  type MassDensityExpression,
  type ScalarExpression,
  type ScalarLike,
  type ScalarVec3Expression,
  type Vec2Expression,
  type Vec3Expression,
} from "./expressions.js";
export {
  combinePhysicalMassProperties,
  inertiaTensorAboutPoint,
  momentOfInertiaAboutAxis,
  physicalMassProperties,
  principalInertia,
  principalRadiiOfGyration,
  radiusOfGyrationAboutAxis,
  worldRadiiOfGyration,
  type InertiaAxis,
  type InertiaPropertySource,
  type PhysicalInertiaTensor,
  type PhysicalMassProperties,
  type PrincipalAxes,
  type PrincipalAxisStatus,
  type PrincipalInertiaDegeneracy,
  type PrincipalInertiaOptions,
  type PrincipalInertiaResult,
} from "./mass-properties.js";
export {
  ArcRef,
  CircleRef,
  LineRef,
  LoopRef,
  PointRef,
  ProfileDefinition,
  SketchBuilder,
  type ArcOptions,
  type CircleOptions,
  type RectangleOptions,
} from "./sketch.js";
export {
  DOCUMENT_SCHEMA,
  DOCUMENT_SCHEMA_V1,
  DOCUMENT_SCHEMA_V2,
  DOCUMENT_VERSION,
  DOCUMENT_VERSION_V1,
  DOCUMENT_VERSION_V2,
  nodeDependencies,
  outputKindForNode,
  type AssemblyInstanceIR,
  type AssemblyNodeIR,
  type BooleanNodeIR,
  type BoxNodeIR,
  type ChamferNodeIR,
  type ChamferNodeIRV1,
  type CircleEntityIR,
  type CylinderNodeIR,
  type DesignDocument,
  type DesignDocumentV1,
  type DesignDocumentV2,
  type DesignConfigurationIR,
  type DesignOutputKind,
  type DraftNeutralPlaneIR,
  type DraftNodeIR,
  type DraftNodeIRV1,
  type EdgeUseIR,
  type ExtrudeNodeIR,
  type FilletNodeIR,
  type FilletNodeIRV1,
  type NodeIR,
  type NodeIRV1,
  type NodeIRV2,
  type OutputKind,
  type ParameterIR,
  type PartNodeIR,
  type PlaneIR,
  type PrincipalPlane,
  type RefIR,
  type RevolveNodeIR,
  type LoftNodeIR,
  type MaterialDefinitionIR,
  type CircularArcPathNodeIR,
  type CompositeCircularArcPathSegmentIR,
  type CompositeLinePathSegmentIR,
  type CompositePathNodeIR,
  type CompositePathSegmentIR,
  type PolylinePathNodeIR,
  type SketchConstraintIR,
  type SketchEntityIR,
  type SketchLoopIR,
  type SketchNodeIR,
  type SketchProfileIR,
  type ShellNodeIR,
  type ShellNodeIRV1,
  type OffsetNodeIR,
  type SphereNodeIR,
  type SweepNodeIR,
  type TransformNodeIR,
  type TransformOperationIR,
  type TopologyCardinalityIR,
  type TopologyOriginRelation,
  type TopologyQueryIR,
  type TopologyQueryIRFor,
  type TopologyQueryIRV1,
  type TopologyQueryIRV2,
  type TopologyReferenceEntryIR,
  type TopologySelectionIR,
  type TopologySelectionIRFor,
  type TopologySelectionIRV1,
  type TopologySelectionIRV2,
  type TopologySourceIR,
} from "./ir.js";
export {
  EvaluatedAssembly,
  EvaluatedDesign,
  EvaluatedPart,
  EvaluatedSolid,
  Evaluator,
  createEvaluator,
  type CreateEvaluatorOptions,
  type BillOfMaterials,
  type BillOfMaterialsItem,
  type EvaluatedMaterial,
  type EvaluatedOccurrence,
  type EvaluatedOutput,
  type EvaluationOptions,
  type ParameterOverride,
  type MassDensitySource,
  type ShapeExportFormat,
} from "./evaluator.js";
export type {
  ConfigurationId,
  MaterialId,
  TopologyReferenceId,
} from "./core/ids.js";
export {
  createManifoldKernel,
  ManifoldKernel,
  type ManifoldKernelOptions,
} from "./manifold-kernel.js";
export {
  COMPOSITE_SWEEP_REFINEMENT_PROTOCOL_VERSION,
  EXACT_INDEXED_TOPOLOGY_EVOLUTION_PROTOCOL_VERSION,
  mergeMeshes,
  GEOMETRY_KERNEL_PROTOCOL_VERSION,
  inspectKernelCompositeSweepCapabilities,
  kernelSupports,
  kernelSupportsTopology,
  transformMesh,
  type BoundingBox,
  type GeometryKernel,
  type InertiaTensor,
  type KernelCapabilityKind,
  type KernelCapabilities,
  type KernelCompositeSweepCapabilities,
  type KernelCompositeSweepCapabilitiesAbsent,
  type KernelCompositeSweepCapabilitiesInspection,
  type KernelCompositeSweepCapabilitiesMalformed,
  type KernelCompositeSweepCapabilitiesMalformedReason,
  type KernelCompositeSweepCapabilitiesValid,
  type KernelCompositeSweepRefinement,
  type KernelExactIndexedTopologyEvolutionCapabilities,
  type KernelExchangeFormat,
  type KernelFeature,
  type KernelFeatureContext,
  type KernelPrimitive,
  type KernelRepresentation,
  type KernelShape,
  type KernelShapeStatus,
  type MeshData,
  type MeshOptions,
  type ResolvedTransformOperation,
  type ShapeMeasurements,
  type TopologyGeometryKernel,
  type VolumetricMassProperties,
} from "./kernel.js";
export {
  curveEnd,
  curveStart,
  numericPlaneBasis,
  pointOnNumericPlane,
  resolvedArcSweep,
  resolvedCurveIsFinite,
  resolvedLoopIsClosed,
  tessellateProfile,
  tessellateResolvedLoop,
  type NumericPlane,
  type NumericPlaneBasis,
  type NumericProfile,
  type ProfileCurveSource,
  type ResolvedArcCurve,
  type ResolvedCircleCurve,
  type ResolvedCurve,
  type ResolvedLineCurve,
  type ResolvedLoop,
  type ResolvedProfile,
  type TessellatedProfile,
} from "./protocol/profile.js";
export {
  resolvedLoopAreaMoments,
  resolvedLoopSignedArea,
  resolvedProfileAreaMoments,
  resolvedProfileLocalAreaMoments,
  type ResolvedLoopAreaMomentsDiagnostics,
  type ResolvedLoopAreaMomentsFailure,
  type ResolvedLoopAreaMomentsFailureReason,
  type ResolvedLoopAreaMomentsResult,
  type ResolvedLoopAreaMomentsSuccess,
  type ResolvedLoopOrientation,
  type ResolvedLoopSignedAreaDiagnostics,
  type ResolvedLoopSignedAreaFailure,
  type ResolvedLoopSignedAreaResult,
  type ResolvedLoopSignedAreaSuccess,
  type ResolvedProfileAreaMomentsDiagnostics,
  type ResolvedProfileAreaMomentsFailure,
  type ResolvedProfileAreaMomentsFailureReason,
  type ResolvedProfileAreaMomentsResult,
  type ResolvedProfileAreaMomentsSuccess,
  type ResolvedProfileLocalAreaMomentsDiagnostics,
  type ResolvedProfileLocalAreaMomentsFailure,
  type ResolvedProfileLocalAreaMomentsResult,
  type ResolvedProfileLocalAreaMomentsSuccess,
} from "./protocol/profile-moments.js";
export {
  LOFT_RULED_SEMANTICS,
  validateRuledSolidLoftProfiles,
  type LoftProfileValidationIssue,
  type ResolvedLoftOptions,
} from "./protocol/loft.js";
export {
  CIRCULAR_ARC_PATH_MIN_POINT_SINE,
  COMPOSITE_PATH_MAX_JUNCTION_SINE,
  POLYLINE_PATH_MIN_CORNER_SINE,
  resolvedCircularArcGeometry,
  resolvedCompositePathSegments,
  resolvedPathEdgeCount,
  resolvedPathInitialTangent,
  resolvedPathSegmentEndTangent,
  resolvedPathSegmentLength,
  resolvedPathSegmentsHaveClearance,
  resolvedPathSegmentStartTangent,
  resolvedPathStart,
  resolvedPolylineSegmentDistance,
  validateResolvedCircularArcPath,
  validateResolvedCompositePath,
  validateResolvedPath,
  validateResolvedPolylinePath,
  type PathValidationIssue,
  type PathValidationReason,
  type ResolvedCircularArcGeometry,
  type ResolvedCircularArcDefinition,
  type ResolvedCircularArcPath,
  type ResolvedCircularArcPathSegment,
  type ResolvedCompositeCircularArcPathSegment,
  type ResolvedCompositeLinePathSegment,
  type ResolvedCompositePath,
  type ResolvedCompositePathSegment,
  type ResolvedLinePathSegment,
  type ResolvedPath,
  type ResolvedPathSegment,
  type ResolvedPolylinePath,
} from "./protocol/path.js";
export {
  COMPOSITE_SWEEP_MAJOR_ARC_ANGLE_EPSILON,
  COMPOSITE_SWEEP_MAJOR_ARC_THRESHOLD,
  COMPOSITE_SWEEP_REFINEMENTS,
  SWEEP_FRAMES,
  SWEEP_TRANSITIONS,
  classifyResolvedCompositeSweepRefinements,
  validateResolvedSweep,
  type CompositeSweepArcRefinementEvidence,
  type CompositeSweepProfileRefinementEvidence,
  type CompositeSweepRefinement,
  type CompositeSweepRefinementClassification,
  type CompositeSweepRefinementClassificationFailure,
  type CompositeSweepRefinementClassificationFailureReason,
  type CompositeSweepRefinementClassificationSuccess,
  type CompositeSweepRefinementEvidence,
  type ResolvedSweepOptions,
  type SweepFrame,
  type SweepTransition,
  type SweepValidationIssue,
  type SweepValidationReason,
} from "./protocol/sweep.js";
export {
  OFFSET_DIRECTIONS,
  OFFSET_JOIN_SEMANTICS,
  type OffsetDirection,
  type ResolvedOffsetOptions,
} from "./protocol/offset.js";
export {
  SHELL_DIRECTIONS,
  SHELL_JOIN_SEMANTICS,
  type ResolvedShellOptions,
  type ShellDirection,
} from "./protocol/shell.js";
export {
  DRAFT_MIN_ANGLE_RADIANS,
  type ResolvedDraftNeutralPlane,
  type ResolvedDraftOptions,
} from "./protocol/draft.js";
export {
  topology,
  type TopologyOriginOptions,
  type TopologyQuery,
  type TopologySelection,
} from "./topology.js";
export {
  resolveTopologySelection,
  topologySelectionRequirements,
  type TopologyResolutionContext,
  type TopologySelectionRequirements,
} from "./topology-resolution.js";
export {
  DEFAULT_TOPOLOGY_SIGNATURE_LIMITS,
  TOPOLOGY_SIGNATURE_PROTOCOL_VERSION,
  captureTopologyReference,
  createTopologyReferenceResolutionSession,
  normalizePersistentTopologyReference,
  resolveTopologyReference,
  type CaptureTopologyReferenceOptions,
  type PersistentTopologyReference,
  type NormalizePersistentTopologyReferenceOptions,
  type ResolveTopologyReferenceOptions,
  type ResolvedTopologyReference,
  type TopologyEdgeGeometrySignature,
  type TopologyFaceGeometrySignature,
  type TopologyGeometrySignature,
  type TopologyMatchEvidence,
  type TopologyMatchTolerance,
  type TopologyNeighborSignature,
  type TopologySignatureLimits,
  type TopologyReferenceResolutionSession,
} from "./topology-signatures.js";
export type {
  EdgeTopologyRole,
  FaceTopologyRole,
  KernelCurveDescriptor,
  KernelEdgeDescriptor,
  KernelFaceDescriptor,
  KernelSurfaceDescriptor,
  KernelTopologyBounds,
  KernelTopologyCapabilities,
  KernelTopologyKey,
  KernelTopologyLineage,
  KernelTopologySignatureCapabilities,
  KernelTopologySnapshot,
  KernelTopologySource,
  TopologyKind,
  TopologyRole,
  TopologyRoleProducer,
  TopologyRoleRule,
  TopologyRoleSource,
} from "./protocol/topology.js";
export {
  EDGE_TOPOLOGY_ROLES,
  FACE_TOPOLOGY_ROLES,
  TOPOLOGY_ROLE_RULES,
  TOPOLOGY_ROLES,
} from "./protocol/topology.js";
export {
  ReferenceSketchSolver,
  createReferenceSketchSolver,
  type SketchSolveContext,
  type SketchSolveStatus,
  type SketchSolverBackend,
  type SketchSolverCapabilities,
  type SolvedSketch,
} from "./solver.js";
export {
  cloneDocument,
  hashDocument,
  migrateDocument,
  parseDocument,
  parseDocumentValue,
  stringifyDocument,
  type StringifyOptions,
  type ParseDocumentOptions,
} from "./serialization.js";
export {
  DesignDocumentSchema,
  DesignDocumentV1Schema,
  DesignDocumentV2Schema,
  ExpressionSchema,
  PersistentTopologyReferenceSchema,
  TopologyQuerySchema,
  TopologyQueryV1Schema,
  TopologyQueryV2Schema,
  TopologySelectionSchema,
  TopologySelectionV1Schema,
  TopologySelectionV2Schema,
} from "./schema.js";
export {
  DEFAULT_DESIGN_DOCUMENT_LIMITS,
  type DesignDocumentLimits,
} from "./document-limits.js";
export { validateDocument } from "./validation.js";
export {
  exportAsciiStl,
  exportBinaryStl,
  exportMesh,
  exportObj,
  type MeshExportFormat,
} from "./exporters.js";
