export {
  CadError,
  diagnostic,
  failure,
  hasErrors,
  success,
  type CadResult,
  type Diagnostic,
  type DiagnosticCode,
  type DiagnosticSeverity,
} from "./core/result.js";
export type { Mat4, Vec2, Vec3 } from "./core/math.js";
export {
  DesignBuilder,
  ModelRef,
  ProfileRef,
  PathRef,
  SolidRef,
  PartRef,
  AssemblyRef,
  AssemblyBuilder,
  design,
  plane,
  tf,
  type DesignOptions,
  type ParameterOptions,
  type Plane,
} from "./design.js";
export {
  Expression,
  Parameter,
  angleVec3,
  cm,
  deg,
  evaluateExpression,
  expr,
  expressionDependencies,
  fromExpressionIR,
  inch,
  meters,
  mm,
  rad,
  scalar,
  scalarVec3,
  vec2,
  vec3,
  type AngleExpression,
  type AngleVec3Expression,
  type Dimension,
  type ExpressionContext,
  type ExpressionIR,
  type LengthExpression,
  type ScalarExpression,
  type ScalarLike,
  type ScalarVec3Expression,
  type Vec2Expression,
  type Vec3Expression,
} from "./expressions.js";
export {
  ArcRef,
  CircleRef,
  LineRef,
  LoopRef,
  PointRef,
  ProfileDefinition,
  SketchBuilder,
  type ArcOptions,
  type CircleOptions,
  type RectangleOptions,
} from "./sketch.js";
export {
  DOCUMENT_SCHEMA,
  DOCUMENT_VERSION,
  nodeDependencies,
  outputKindForNode,
  type AssemblyInstanceIR,
  type AssemblyNodeIR,
  type BooleanNodeIR,
  type BoxNodeIR,
  type ChamferNodeIR,
  type CircleEntityIR,
  type CylinderNodeIR,
  type DesignDocument,
  type DesignOutputKind,
  type DraftNeutralPlaneIR,
  type DraftNodeIR,
  type EdgeUseIR,
  type ExtrudeNodeIR,
  type FilletNodeIR,
  type NodeIR,
  type OutputKind,
  type ParameterIR,
  type PartNodeIR,
  type PlaneIR,
  type PrincipalPlane,
  type RefIR,
  type RevolveNodeIR,
  type LoftNodeIR,
  type PolylinePathNodeIR,
  type SketchConstraintIR,
  type SketchEntityIR,
  type SketchLoopIR,
  type SketchNodeIR,
  type SketchProfileIR,
  type ShellNodeIR,
  type OffsetNodeIR,
  type SphereNodeIR,
  type SweepNodeIR,
  type TransformNodeIR,
  type TransformOperationIR,
  type TopologyCardinalityIR,
  type TopologyOriginRelation,
  type TopologyQueryIR,
  type TopologySelectionIR,
  type TopologySourceIR,
} from "./ir.js";
export {
  EvaluatedAssembly,
  EvaluatedDesign,
  EvaluatedPart,
  EvaluatedSolid,
  Evaluator,
  createEvaluator,
  type CreateEvaluatorOptions,
  type EvaluatedOccurrence,
  type EvaluatedOutput,
  type EvaluationOptions,
  type ParameterOverride,
  type ShapeExportFormat,
} from "./evaluator.js";
export {
  createManifoldKernel,
  ManifoldKernel,
  type ManifoldKernelOptions,
} from "./manifold-kernel.js";
export {
  EXACT_INDEXED_TOPOLOGY_EVOLUTION_PROTOCOL_VERSION,
  mergeMeshes,
  GEOMETRY_KERNEL_PROTOCOL_VERSION,
  kernelSupports,
  kernelSupportsTopology,
  transformMesh,
  type BoundingBox,
  type GeometryKernel,
  type KernelCapabilityKind,
  type KernelCapabilities,
  type KernelExactIndexedTopologyEvolutionCapabilities,
  type KernelExchangeFormat,
  type KernelFeature,
  type KernelFeatureContext,
  type KernelPrimitive,
  type KernelRepresentation,
  type KernelShape,
  type KernelShapeStatus,
  type MeshData,
  type MeshOptions,
  type ResolvedTransformOperation,
  type ShapeMeasurements,
  type TopologyGeometryKernel,
} from "./kernel.js";
export {
  curveEnd,
  curveStart,
  resolvedLoopIsClosed,
  tessellateProfile,
  tessellateResolvedLoop,
  type NumericPlane,
  type NumericProfile,
  type ProfileCurveSource,
  type ResolvedArcCurve,
  type ResolvedCircleCurve,
  type ResolvedCurve,
  type ResolvedLineCurve,
  type ResolvedLoop,
  type ResolvedProfile,
  type TessellatedProfile,
} from "./protocol/profile.js";
export {
  LOFT_RULED_SEMANTICS,
  validateRuledSolidLoftProfiles,
  type LoftProfileValidationIssue,
  type ResolvedLoftOptions,
} from "./protocol/loft.js";
export {
  POLYLINE_PATH_MIN_CORNER_SINE,
  resolvedPolylineSegmentDistance,
  validateResolvedPolylinePath,
  type PathValidationIssue,
  type PathValidationReason,
  type ResolvedPath,
  type ResolvedPolylinePath,
} from "./protocol/path.js";
export {
  SWEEP_FRAMES,
  SWEEP_TRANSITIONS,
  validateResolvedSweep,
  type ResolvedSweepOptions,
  type SweepFrame,
  type SweepTransition,
  type SweepValidationIssue,
  type SweepValidationReason,
} from "./protocol/sweep.js";
export {
  OFFSET_DIRECTIONS,
  OFFSET_JOIN_SEMANTICS,
  type OffsetDirection,
  type ResolvedOffsetOptions,
} from "./protocol/offset.js";
export {
  SHELL_DIRECTIONS,
  SHELL_JOIN_SEMANTICS,
  type ResolvedShellOptions,
  type ShellDirection,
} from "./protocol/shell.js";
export {
  DRAFT_MIN_ANGLE_RADIANS,
  type ResolvedDraftNeutralPlane,
  type ResolvedDraftOptions,
} from "./protocol/draft.js";
export {
  topology,
  type TopologyOriginOptions,
  type TopologyQuery,
  type TopologySelection,
} from "./topology.js";
export {
  resolveTopologySelection,
  type TopologyResolutionContext,
} from "./topology-resolution.js";
export type {
  EdgeTopologyRole,
  FaceTopologyRole,
  KernelCurveDescriptor,
  KernelEdgeDescriptor,
  KernelFaceDescriptor,
  KernelSurfaceDescriptor,
  KernelTopologyBounds,
  KernelTopologyCapabilities,
  KernelTopologyKey,
  KernelTopologyLineage,
  KernelTopologySnapshot,
  KernelTopologySource,
  TopologyKind,
  TopologyRole,
  TopologyRoleProducer,
  TopologyRoleRule,
  TopologyRoleSource,
} from "./protocol/topology.js";
export {
  EDGE_TOPOLOGY_ROLES,
  FACE_TOPOLOGY_ROLES,
  TOPOLOGY_ROLE_RULES,
  TOPOLOGY_ROLES,
} from "./protocol/topology.js";
export {
  ReferenceSketchSolver,
  createReferenceSketchSolver,
  type SketchSolveContext,
  type SketchSolveStatus,
  type SketchSolverBackend,
  type SketchSolverCapabilities,
  type SolvedSketch,
} from "./solver.js";
export {
  cloneDocument,
  hashDocument,
  migrateDocument,
  parseDocument,
  parseDocumentValue,
  stringifyDocument,
  type StringifyOptions,
} from "./serialization.js";
export {
  DesignDocumentSchema,
  ExpressionSchema,
  TopologyQuerySchema,
  TopologySelectionSchema,
} from "./schema.js";
export { validateDocument } from "./validation.js";
export {
  exportAsciiStl,
  exportBinaryStl,
  exportMesh,
  exportObj,
  type MeshExportFormat,
} from "./exporters.js";
