export {
  CadError,
  diagnostic,
  failure,
  hasErrors,
  success,
  type CadResult,
  type Diagnostic,
  type DiagnosticCode,
  type DiagnosticSeverity,
} from "./core/result.js";
export type { Mat4, Vec2, Vec3 } from "./core/math.js";
export {
  DesignBuilder,
  ModelRef,
  ProfileRef,
  PathRef,
  SolidRef,
  PartRef,
  AssemblyRef,
  MaterialRef,
  TopologyReferenceRef,
  AssemblyBuilder,
  ConfigurationBuilder,
  design,
  plane,
  tf,
  type DesignOptions,
  type MaterialOptions,
  type PartOptions,
  type CompositePathSegmentExpression,
  type ConfigurationOptions,
  type ParameterOptions,
  type Plane,
  type TopologyReferenceOptions,
} from "./design.js";
export {
  DESIGN_IMPACT_REPORT_VERSION,
  analyzeDesignImpact,
  type AnalyzeDesignImpactOptions,
  type DesignConfigurationImpact,
  type DesignConfigurationImpactReason,
  type DesignImpactChanges,
  type DesignImpactReport,
  type DesignImpactSeedInventory,
  type DesignMaterialImpact,
  type DesignMaterialImpactReason,
  type DesignNodeImpact,
  type DesignNodeImpactReason,
  type DesignOutputImpact,
  type DesignParameterImpact,
  type DesignParameterImpactReason,
} from "./design-impact.js";
export {
  DEFAULT_FEATURE_HASH_LIMITS,
  DESIGN_FEATURE_HASH_REPORT_VERSION,
  FEATURE_HASH_ALGORITHM,
  FEATURE_HASH_PREFIX,
  FEATURE_HASH_PROTOCOL_VERSION,
  hashDesignFeatures,
  type DesignFeatureHashEntry,
  type DesignFeatureHashReport,
  type DesignFeatureOutputHash,
  type FeatureHash,
  type FeatureHashLimits,
  type HashDesignFeaturesOptions,
} from "./feature-hashes.js";
export {
  ARTIFACT_CACHE_INTEGRITY_ALGORITHM,
  ARTIFACT_CACHE_KEY_PREFIX,
  ARTIFACT_CACHE_MAX_KEY_MATERIAL_BYTES,
  ARTIFACT_CACHE_NAMESPACE,
  ARTIFACT_CACHE_PROTOCOL_VERSION,
  ARTIFACT_EVALUATION_SEMANTICS_VERSION,
  DEFAULT_ARTIFACT_CACHE_LIMITS,
  ArtifactCacheStoreLimitError,
  ArtifactCacheSession,
  MemoryArtifactCacheStore,
  createArtifactCacheRecord,
  createArtifactCacheSession,
  createKernelShapeArtifactCacheKey,
  deleteArtifactCacheRecord,
  inspectKernelShapeArtifactSupport,
  normalizeArtifactCacheLimits,
  readArtifactCacheRecord,
  validateArtifactCacheRecord,
  writeArtifactCacheRecord,
  type ArtifactCacheDeleteContext,
  type ArtifactCacheEvent,
  type ArtifactCacheFeature,
  type ArtifactCacheIntegrityV1,
  type ArtifactCacheKey,
  type ArtifactCacheKeyMaterialV1,
  type ArtifactCacheLimits,
  type ArtifactCacheMode,
  type ArtifactCacheOptions,
  type ArtifactCacheReadResult,
  type ArtifactCacheRecordV1,
  type ArtifactCacheSessionOperationOptions,
  type ArtifactCacheSessionUsage,
  type ArtifactCacheStore,
  type ArtifactCacheStoreContext,
  type ArtifactCacheStoreValue,
  type ArtifactFeatureHashV1,
  type KernelShapeArtifactCacheKey,
  type KernelShapeArtifactSupportInspection,
} from "./artifact-cache.js";
export {
  Expression,
  Parameter,
  angleVec3,
  cm,
  deg,
  evaluateExpression,
  expr,
  expressionDependencies,
  fromExpressionIR,
  gramsPerCubicCentimeter,
  inch,
  kgPerCubicMeter,
  kgPerCubicMillimeter,
  meters,
  mm,
  rad,
  scalar,
  scalarVec3,
  vec2,
  vec3,
  type AngleExpression,
  type AngleVec3Expression,
  type Dimension,
  type ExpressionContext,
  type ExpressionIR,
  type LengthExpression,
  type MassDensityExpression,
  type ScalarExpression,
  type ScalarLike,
  type ScalarVec3Expression,
  type Vec2Expression,
  type Vec3Expression,
} from "./expressions.js";
export {
  combinePhysicalMassProperties,
  inertiaTensorAboutPoint,
  momentOfInertiaAboutAxis,
  physicalMassProperties,
  principalInertia,
  principalRadiiOfGyration,
  radiusOfGyrationAboutAxis,
  worldRadiiOfGyration,
  type InertiaAxis,
  type InertiaPropertySource,
  type PhysicalInertiaTensor,
  type PhysicalMassProperties,
  type PrincipalAxes,
  type PrincipalAxisStatus,
  type PrincipalInertiaDegeneracy,
  type PrincipalInertiaOptions,
  type PrincipalInertiaResult,
} from "./mass-properties.js";
export {
  ArcRef,
  CircleRef,
  LineRef,
  LoopRef,
  PointRef,
  ProfileDefinition,
  SketchBuilder,
  type ArcOptions,
  type CircleOptions,
  type RectangleOptions,
} from "./sketch.js";
export {
  DOCUMENT_SCHEMA,
  DOCUMENT_SCHEMA_V1,
  DOCUMENT_SCHEMA_V2,
  DOCUMENT_SCHEMA_V3,
  DOCUMENT_SCHEMA_V4,
  DOCUMENT_SCHEMA_V5,
  DOCUMENT_SCHEMA_V6,
  DOCUMENT_VERSION,
  DOCUMENT_VERSION_V1,
  DOCUMENT_VERSION_V2,
  DOCUMENT_VERSION_V3,
  DOCUMENT_VERSION_V4,
  DOCUMENT_VERSION_V5,
  DOCUMENT_VERSION_V6,
  NODE_KINDS,
  NODE_KINDS_V1,
  NODE_KINDS_V2,
  NODE_KINDS_V3,
  NODE_KINDS_V4,
  NODE_KINDS_V5,
  NODE_KINDS_V6,
  nodeDependencies,
  nodeParameterDependencies,
  outputKindForNode,
  type AssemblyInstanceIR,
  type AssemblyNodeIR,
  type BooleanNodeIR,
  type BoxNodeIR,
  type ChamferNodeIR,
  type ChamferNodeIRV1,
  type ChamferNodeIRV2,
  type ChamferNodeIRV3,
  type ChamferNodeIRV4,
  type ChamferNodeIRV5,
  type ChamferNodeIRV6,
  type CircleEntityIR,
  type CylinderNodeIR,
  type DesignDocument,
  type DesignDocumentV1,
  type DesignDocumentV2,
  type DesignDocumentV3,
  type DesignDocumentV4,
  type DesignDocumentV5,
  type DesignDocumentV6,
  type DesignConfigurationIR,
  type DesignOutputKind,
  type DraftNeutralPlaneIR,
  type DraftNodeIR,
  type DraftNodeIRV1,
  type DraftNodeIRV2,
  type DraftNodeIRV3,
  type DraftNodeIRV4,
  type DraftNodeIRV5,
  type DraftNodeIRV6,
  type EdgeUseIR,
  type ExtrudeNodeIR,
  type FilletNodeIR,
  type FilletNodeIRV1,
  type FilletNodeIRV2,
  type FilletNodeIRV3,
  type FilletNodeIRV4,
  type FilletNodeIRV5,
  type FilletNodeIRV6,
  type NodeKind,
  type NodeKindV1,
  type NodeKindV2,
  type NodeKindV3,
  type NodeKindV4,
  type NodeKindV5,
  type NodeKindV6,
  type NodeIR,
  type NodeIRV1,
  type NodeIRV2,
  type NodeIRV3,
  type NodeIRV4,
  type NodeIRV5,
  type NodeIRV6,
  type OutputKind,
  type ParameterIR,
  type PartNodeIR,
  type PlaneIR,
  type PrincipalPlane,
  type RefIR,
  type RevolveNodeIR,
  type LoftNodeIR,
  type MaterialDefinitionIR,
  type CircularArcPathNodeIR,
  type CompositeCircularArcPathSegmentIR,
  type CompositeLinePathSegmentIR,
  type CompositePathNodeIR,
  type CompositePathSegmentIR,
  type PolylinePathNodeIR,
  type SketchConstraintIR,
  type SketchEntityIR,
  type SketchLoopIR,
  type SketchNodeIR,
  type SketchProfileIR,
  type ShellNodeIR,
  type ShellNodeIRV1,
  type ShellNodeIRV2,
  type ShellNodeIRV3,
  type ShellNodeIRV4,
  type ShellNodeIRV5,
  type ShellNodeIRV6,
  type OffsetNodeIR,
  type SphereNodeIR,
  type SweepNodeIR,
  type TransformNodeIR,
  type TransformOperationIR,
  type TopologyCardinalityIR,
  type TopologyOriginRelation,
  type TopologyQueryIR,
  type TopologyQueryIRFor,
  type TopologyQueryIRV1,
  type TopologyQueryIRV2,
  type TopologyQueryIRV3,
  type TopologyQueryIRV4,
  type TopologyQueryIRV5,
  type TopologyQueryIRV6,
  type TopologyReferenceEntryIR,
  type TopologyReferenceEntryIRV2,
  type TopologyReferenceEntryIRV3,
  type TopologyReferenceEntryIRV4,
  type TopologyReferenceEntryIRV5,
  type TopologyReferenceEntryIRV6,
  type TopologySelectionIR,
  type TopologySelectionIRFor,
  type TopologySelectionIRV1,
  type TopologySelectionIRV2,
  type TopologySelectionIRV3,
  type TopologySelectionIRV4,
  type TopologySelectionIRV5,
  type TopologySelectionIRV6,
  type TopologySourceIR,
} from "./ir.js";
export {
  EvaluatedAssembly,
  EvaluatedDesign,
  EvaluatedPart,
  EvaluatedSolid,
  Evaluator,
  EVALUATOR_PROFILES,
  createEvaluator,
  type CreateEvaluatorOptions,
  type BillOfMaterials,
  type BillOfMaterialsItem,
  type EvaluatedMaterial,
  type EvaluatedOccurrence,
  type EvaluatedOutput,
  type EvaluatorProfile,
  type EvaluatorProfileInspection,
  type EvaluationOptions,
  type ParameterOverride,
  type MassDensitySource,
  type BinaryShapeExportFormat,
  type ShapeExportFormat,
  type TextShapeExportFormat,
  inspectEvaluatorProfile,
} from "./evaluator.js";
export type {
  ConfigurationId,
  EntityId,
  MaterialId,
  NodeId,
  OutputName,
  ParameterId,
  TopologyReferenceId,
} from "./core/ids.js";
export {
  createManifoldKernel,
  ManifoldKernel,
  type ManifoldKernelOptions,
} from "./manifold-kernel.js";
export {
  COMPOSITE_SWEEP_REFINEMENT_PROTOCOL_VERSION,
  EXACT_INDEXED_TOPOLOGY_EVOLUTION_PROTOCOL_VERSION,
  KERNEL_DOCUMENT_BODY_IMPORT_PROTOCOL_VERSION,
  KERNEL_SHAPE_ARTIFACT_MAX_COMPATIBILITY_FINGERPRINT_BYTES,
  KERNEL_SHAPE_ARTIFACT_PROTOCOL_VERSION,
  mergeMeshes,
  GEOMETRY_KERNEL_PROTOCOL_VERSION,
  inspectKernelCompositeSweepCapabilities,
  inspectKernelDocumentBodyImportCapabilities,
  kernelSupports,
  kernelSupportsDocumentBodyImport,
  kernelSupportsTopology,
  transformMesh,
  type BoundingBox,
  type GeometryKernel,
  type Awaitable,
  type InertiaTensor,
  type KernelCapabilityKind,
  type KernelCapabilities,
  type KernelCompositeSweepCapabilities,
  type KernelCompositeSweepCapabilitiesAbsent,
  type KernelCompositeSweepCapabilitiesInspection,
  type KernelCompositeSweepCapabilitiesMalformed,
  type KernelCompositeSweepCapabilitiesMalformedReason,
  type KernelCompositeSweepCapabilitiesValid,
  type KernelCompositeSweepRefinement,
  type KernelDocumentBodyImportCapabilities,
  type KernelDocumentBodyImportCapabilitiesAbsent,
  type KernelDocumentBodyImportCapabilitiesInspection,
  type KernelDocumentBodyImportCapabilitiesMalformed,
  type KernelDocumentBodyImportCapabilitiesMalformedReason,
  type KernelDocumentBodyImportCapabilitiesValid,
  type KernelDocumentBodyImportFormatCapabilities,
  type KernelDocumentBodyImportOptions,
  type KernelDocumentBodyImportUnits,
  type KernelDocumentBodyLengthUnit,
  type KernelDocumentBodyUnitMode,
  type KernelExactIndexedTopologyEvolutionCapabilities,
  type KernelExchangeFormat,
  type KernelFeature,
  type KernelFeatureContext,
  type KernelPrimitive,
  type KernelRepresentation,
  type KernelShape,
  type KernelShapeArtifactCapabilities,
  type KernelShapeArtifactContext,
  type KernelShapeStatus,
  type MeshData,
  type MeshOptions,
  type ResolvedTransformOperation,
  type ShapeMeasurements,
  type TopologyGeometryKernel,
  type VolumetricMassProperties,
} from "./kernel.js";
export {
  curveEnd,
  curveStart,
  numericPlaneBasis,
  pointOnNumericPlane,
  resolvedArcSweep,
  resolvedCurveIsFinite,
  resolvedLoopIsClosed,
  tessellateProfile,
  tessellateResolvedLoop,
  type NumericPlane,
  type NumericPlaneBasis,
  type NumericProfile,
  type ProfileCurveSource,
  type ResolvedArcCurve,
  type ResolvedCircleCurve,
  type ResolvedCurve,
  type ResolvedLineCurve,
  type ResolvedLoop,
  type ResolvedProfile,
  type TessellatedProfile,
} from "./protocol/profile.js";
export {
  resolvedLoopAreaMoments,
  resolvedLoopSignedArea,
  resolvedProfileAreaMoments,
  resolvedProfileLocalAreaMoments,
  type ResolvedLoopAreaMomentsDiagnostics,
  type ResolvedLoopAreaMomentsFailure,
  type ResolvedLoopAreaMomentsFailureReason,
  type ResolvedLoopAreaMomentsResult,
  type ResolvedLoopAreaMomentsSuccess,
  type ResolvedLoopOrientation,
  type ResolvedLoopSignedAreaDiagnostics,
  type ResolvedLoopSignedAreaFailure,
  type ResolvedLoopSignedAreaResult,
  type ResolvedLoopSignedAreaSuccess,
  type ResolvedProfileAreaMomentsDiagnostics,
  type ResolvedProfileAreaMomentsFailure,
  type ResolvedProfileAreaMomentsFailureReason,
  type ResolvedProfileAreaMomentsResult,
  type ResolvedProfileAreaMomentsSuccess,
  type ResolvedProfileLocalAreaMomentsDiagnostics,
  type ResolvedProfileLocalAreaMomentsFailure,
  type ResolvedProfileLocalAreaMomentsResult,
  type ResolvedProfileLocalAreaMomentsSuccess,
} from "./protocol/profile-moments.js";
export {
  LOFT_RULED_SEMANTICS,
  validateRuledSolidLoftProfiles,
  type LoftProfileValidationIssue,
  type ResolvedLoftOptions,
} from "./protocol/loft.js";
export {
  CIRCULAR_ARC_PATH_MIN_POINT_SINE,
  COMPOSITE_PATH_MAX_JUNCTION_SINE,
  POLYLINE_PATH_MIN_CORNER_SINE,
  resolvedCircularArcGeometry,
  resolvedCompositePathSegments,
  resolvedPathEdgeCount,
  resolvedPathInitialTangent,
  resolvedPathSegmentEndTangent,
  resolvedPathSegmentLength,
  resolvedPathSegmentsHaveClearance,
  resolvedPathSegmentStartTangent,
  resolvedPathStart,
  resolvedPolylineSegmentDistance,
  validateResolvedCircularArcPath,
  validateResolvedCompositePath,
  validateResolvedPath,
  validateResolvedPolylinePath,
  type PathValidationIssue,
  type PathValidationReason,
  type ResolvedCircularArcGeometry,
  type ResolvedCircularArcDefinition,
  type ResolvedCircularArcPath,
  type ResolvedCircularArcPathSegment,
  type ResolvedCompositeCircularArcPathSegment,
  type ResolvedCompositeLinePathSegment,
  type ResolvedCompositePath,
  type ResolvedCompositePathSegment,
  type ResolvedLinePathSegment,
  type ResolvedPath,
  type ResolvedPathSegment,
  type ResolvedPolylinePath,
} from "./protocol/path.js";
export {
  COMPOSITE_SWEEP_MAJOR_ARC_ANGLE_EPSILON,
  COMPOSITE_SWEEP_MAJOR_ARC_THRESHOLD,
  COMPOSITE_SWEEP_REFINEMENTS,
  SWEEP_FRAMES,
  SWEEP_TRANSITIONS,
  classifyResolvedCompositeSweepRefinements,
  validateResolvedSweep,
  type CompositeSweepArcRefinementEvidence,
  type CompositeSweepProfileRefinementEvidence,
  type CompositeSweepRefinement,
  type CompositeSweepRefinementClassification,
  type CompositeSweepRefinementClassificationFailure,
  type CompositeSweepRefinementClassificationFailureReason,
  type CompositeSweepRefinementClassificationSuccess,
  type CompositeSweepRefinementEvidence,
  type ResolvedSweepOptions,
  type SweepFrame,
  type SweepTransition,
  type SweepValidationIssue,
  type SweepValidationReason,
} from "./protocol/sweep.js";
export {
  OFFSET_DIRECTIONS,
  OFFSET_JOIN_SEMANTICS,
  type OffsetDirection,
  type ResolvedOffsetOptions,
} from "./protocol/offset.js";
export {
  SHELL_DIRECTIONS,
  SHELL_JOIN_SEMANTICS,
  type ResolvedShellOptions,
  type ShellDirection,
} from "./protocol/shell.js";
export {
  DRAFT_MIN_ANGLE_RADIANS,
  type ResolvedDraftNeutralPlane,
  type ResolvedDraftOptions,
} from "./protocol/draft.js";
export {
  topology,
  type TopologyOriginOptions,
  type TopologyQuery,
  type TopologySelection,
} from "./topology.js";
export {
  TOPOLOGY_SELECTION_EXPLANATION_VERSION,
  explainTopologySelection,
  resolveTopologySelection,
  topologySelectionRequirements,
  type TopologyResolutionContext,
  type TopologySelectionResolutionExplanation,
  type TopologySelectionResolutionExplanationBase,
  type TopologySelectionRequirements,
} from "./topology-resolution.js";
export {
  DEFAULT_TOPOLOGY_SIGNATURE_LIMITS,
  TOPOLOGY_REFERENCE_EXPLANATION_VERSION,
  TOPOLOGY_SIGNATURE_PROTOCOL_VERSION,
  TOPOLOGY_SIGNATURE_PROTOCOL_VERSION_V1,
  TOPOLOGY_SIGNATURE_PROTOCOL_VERSION_V2,
  captureTopologyReference,
  createTopologyReferenceResolutionSession,
  explainTopologyReference,
  normalizePersistentTopologyReference,
  resolveTopologyReference,
  type CaptureTopologyReferenceOptions,
  type ExplainableTopologyReferenceResolutionSession,
  type PersistentTopologyReference,
  type PersistentTopologyReferenceV2,
  type PersistentTopologyReferenceV3,
  type PersistentTopologyReferenceV4,
  type PersistentTopologyReferenceV5,
  type PersistentTopologyReferenceV6,
  type PersistentTopologyReferenceProtocolV1,
  type PersistentTopologyReferenceProtocolV2,
  type PersistentTopologyLineage,
  type PersistentTopologyLineageV2,
  type PersistentTopologyLineageV3,
  type PersistentTopologyLineageV4,
  type PersistentTopologyLineageV5,
  type PersistentTopologyLineageV6,
  type NormalizePersistentTopologyReferenceOptions,
  type ResolveTopologyReferenceOptions,
  type ResolvedTopologyReference,
  type TopologyEdgeGeometrySignature,
  type TopologyFaceGeometrySignature,
  type TopologyVertexGeometrySignature,
  type TopologyGeometrySignature,
  type TopologyMatchEvidence,
  type TopologyMatchTolerance,
  type TopologyNeighborSignature,
  type TopologyNeighborSignatureProtocolV1,
  type TopologyNeighborSignatureProtocolV2,
  type TopologyNeighborSignatureV2,
  type TopologyNeighborSignatureV3,
  type TopologyNeighborSignatureV4,
  type TopologyNeighborSignatureV5,
  type TopologyNeighborSignatureV6,
  type TopologyReferenceResolutionExplanation,
  type TopologyReferenceResolutionExplanationBase,
  type TopologyReferenceStrategySummary,
  type TopologySignatureLimits,
  type TopologyReferenceResolutionSession,
} from "./topology-signatures.js";
export type {
  EdgeTopologyRole,
  EdgeTopologyRoleV1,
  EdgeTopologyRoleV2,
  EdgeTopologyRoleV3,
  EdgeTopologyRoleV4,
  EdgeTopologyRoleV5,
  EdgeTopologyRoleV6,
  FaceTopologyRole,
  FaceTopologyRoleV1,
  FaceTopologyRoleV2,
  FaceTopologyRoleV3,
  FaceTopologyRoleV4,
  FaceTopologyRoleV5,
  FaceTopologyRoleV6,
  KernelCurveDescriptor,
  KernelEdgeDescriptor,
  KernelFaceDescriptor,
  KernelVertexDescriptor,
  KernelSurfaceDescriptor,
  KernelTopologyBounds,
  KernelTopologyCapabilities,
  KernelTopologyKey,
  KernelTopologyLineage,
  KernelTopologySignatureCapabilities,
  KernelTopologySignatureCapabilitiesV1,
  KernelTopologySignatureCapabilitiesV2,
  KernelTopologySnapshot,
  KernelTopologySource,
  TopologyKind,
  TopologyKindV1,
  TopologyKindV2,
  TopologyRole,
  TopologyRoleV1,
  TopologyRoleV2,
  TopologyRoleV3,
  TopologyRoleV4,
  TopologyRoleV5,
  TopologyRoleV6,
  TopologyRoleProducer,
  TopologyRoleRule,
  TopologyRoleSource,
  VertexTopologyRole,
  VertexTopologyRoleV1,
  VertexTopologyRoleV2,
  VertexTopologyRoleV3,
  VertexTopologyRoleV4,
  VertexTopologyRoleV5,
  VertexTopologyRoleV6,
} from "./protocol/topology.js";
export {
  EDGE_TOPOLOGY_ROLES,
  EDGE_TOPOLOGY_ROLES_V1,
  EDGE_TOPOLOGY_ROLES_V2,
  EDGE_TOPOLOGY_ROLES_V3,
  EDGE_TOPOLOGY_ROLES_V4,
  EDGE_TOPOLOGY_ROLES_V5,
  EDGE_TOPOLOGY_ROLES_V6,
  FACE_TOPOLOGY_ROLES,
  FACE_TOPOLOGY_ROLES_V1,
  FACE_TOPOLOGY_ROLES_V2,
  FACE_TOPOLOGY_ROLES_V3,
  FACE_TOPOLOGY_ROLES_V4,
  FACE_TOPOLOGY_ROLES_V5,
  FACE_TOPOLOGY_ROLES_V6,
  TOPOLOGY_ROLE_RULES,
  TOPOLOGY_ROLES,
  TOPOLOGY_ROLES_V1,
  TOPOLOGY_ROLES_V2,
  TOPOLOGY_ROLES_V3,
  TOPOLOGY_ROLES_V4,
  TOPOLOGY_ROLES_V5,
  TOPOLOGY_ROLES_V6,
  VERTEX_TOPOLOGY_ROLES,
  VERTEX_TOPOLOGY_ROLES_V1,
  VERTEX_TOPOLOGY_ROLES_V2,
  VERTEX_TOPOLOGY_ROLES_V3,
  VERTEX_TOPOLOGY_ROLES_V4,
  VERTEX_TOPOLOGY_ROLES_V5,
  VERTEX_TOPOLOGY_ROLES_V6,
} from "./protocol/topology.js";
export {
  ReferenceSketchSolver,
  createReferenceSketchSolver,
  type SketchSolveContext,
  type SketchSolveStatus,
  type SketchSolverBackend,
  type SketchSolverCapabilities,
  type SolvedSketch,
} from "./solver.js";
export {
  cloneDocument,
  hashDocument,
  migrateDocument,
  parseDocument,
  parseDocumentValue,
  stringifyDocument,
  type StringifyOptions,
  type ParseDocumentOptions,
} from "./serialization.js";
export {
  DesignDocumentSchema,
  DesignDocumentV1Schema,
  DesignDocumentV2Schema,
  DesignDocumentV3Schema,
  DesignDocumentV4Schema,
  DesignDocumentV5Schema,
  DesignDocumentV6Schema,
  ExpressionSchema,
  NodeSchema,
  NodeV1Schema,
  NodeV2Schema,
  NodeV3Schema,
  NodeV4Schema,
  NodeV5Schema,
  NodeV6Schema,
  PersistentTopologyReferenceSchema,
  PersistentTopologyReferenceV2Schema,
  PersistentTopologyReferenceV3Schema,
  PersistentTopologyReferenceV4Schema,
  PersistentTopologyReferenceV5Schema,
  PersistentTopologyReferenceV6Schema,
  TopologyReferenceEntrySchema,
  TopologyReferenceEntryV2Schema,
  TopologyReferenceEntryV3Schema,
  TopologyReferenceEntryV4Schema,
  TopologyReferenceEntryV5Schema,
  TopologyReferenceEntryV6Schema,
  TopologyQuerySchema,
  TopologyQueryV1Schema,
  TopologyQueryV2Schema,
  TopologyQueryV3Schema,
  TopologyQueryV4Schema,
  TopologyQueryV5Schema,
  TopologyQueryV6Schema,
  TopologySelectionSchema,
  TopologySelectionV1Schema,
  TopologySelectionV2Schema,
  TopologySelectionV3Schema,
  TopologySelectionV4Schema,
  TopologySelectionV5Schema,
  TopologySelectionV6Schema,
} from "./schema.js";
export {
  DEFAULT_DESIGN_DOCUMENT_LIMITS,
  type DesignDocumentLimits,
} from "./document-limits.js";
export { validateDocument } from "./validation.js";
export {
  exportAsciiStl,
  exportBinaryStl,
  exportMesh,
  exportObj,
  type MeshExportFormat,
} from "./exporters.js";
